apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "serviio.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "serviio.name" $ }}
  template:
    metadata:
      labels:
        app: {{ template "serviio.name" $ }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      hostNetwork: true
      containers:
      - name: serviio
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 1900
          protocol: UDP
        - containerPort: 8895
        - containerPort: 23423
        # Mount the NFS volume in the container
        volumeMounts:
{{- range $key, $val := .Values.content }}
        - name: {{ $key }}
          mountPath: {{ $val.mount }}
{{- end }}
        - mountPath: /opt/serviio/library
          subPath: library
          name: {{ include "serviio.name" . }}
      # Add the NFS volume to the Pod
      volumes:
{{- range $key, $val := .Values.content }}
      - name: {{ $key }}
      {{- if $val.nfs }}
        # Set the NFS server and path to the share
        nfs:
          server: {{ $val.nfs.server }}
          path: {{ $val.nfs.path }}
      {{- end }}
{{- end }}
      - name: serviio
        persistentVolumeClaim:
          claimName: {{ include "serviio.name" . }}
      affinity:
        {{- if .Values.affinity }}
{{ toYaml .Values.affinity | trim | indent 8 }}
        {{- end }}