kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "serviio.name" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
