{{ if .Values.storage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "serviio.name" . }}
spec:
  accessModes:
    - {{ (.Values.storage.node).type | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "8Gi" }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}