apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviio.fullname" . }}-dlna
  annotations:
    metallb.io/allow-shared-ip: {{ include "serviio.name" . }}
spec:
  type: NodePort
  selector:
    app:  {{ include "serviio.name" . }}
  ports:
    - name:  {{ include "serviio.name" . }}-content
      port: 31900
      targetPort: 1900
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviio.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app:  {{ include "serviio.name" . }}
  ports:
    - name:  {{ include "serviio.name" . }}-console
      port: 80
      targetPort: 23423
    - name:  {{ include "serviio.name" . }}-dlna
      port: 8895
      targetPort: 8895
